### ISSUE TITLE
Can we include a pre-baked npm cache in the build image to speed up the builds?

### ISSUE THREAD

**Issue by anttiviljami** [into-docker/into-docker-create-react-app#1]

**Comment by xsc** [comment]
Could you elaborate? I'm assuming that you mean leveraging the fact that we are focusing on create-react-app to preload dependencies?

I feel like this could be a maintenance nightmare to keep up with dependency versions. In my tests, for example, it seemed that the cache did not help when I changed the version of `react`.

There is a caching mechanism (`into --cache <PATH_TO_CACHE_TAR> ...`) that [currently caches `node_modules`](https://github.com/into-docker/into-docker-create-react-app/blob/24c1652df9a21136dc1ac90c1ed2893dfb58b99a/into/cache). We could add `~/.npm` to that.

These lead to a speed up in follow-up runs, not the initial one, though, and (probably) only if you don't use `npm ci` (see below).

---

Just for completeness, I did some tests regarding caching:

When caching `node_modules`:
- This seems to have a negative effect when using `npm ci` since it costs time to remove the folder (which `npm ci` always does).
- It had a huge effect with `npm install` (saved >50% of build time) but that would not use the lock file.
- It had the same effect with `yarn install` but, again, would not use the lock file
- However, it also worked with `yarn --frozen-lockfile` which complains if the lockfile needs updating.

When caching `~/.npm`:
- This reduced runtime of `npm ci` by around 25%, however you had to run `npm ci --prefer-offline --no-audit` to achieve this.

**Comment by anttiviljami** [comment]
Good research! My naive thought was to just basically pre-run `npm ci` in the docker build, which would save the packages in ~/.npm. Your research seems to show that the effect of this is minimal.
